import axios from "axios";
import { HUGGINGFACE_API_TOKEN } from "@env";

const API_URL = "https://api-inference.huggingface.co/models/facebook/blenderbot-400M-distill";
/**
 * Fetches a response from the Hugging Face model based on user input.
 * @param {string} inputText - The user's journal or chat text.
 * @returns {Promise<string>} - The response generated by the model.
 */
export const fetchHuggingFaceResponse = async (inputText) => {
  try {
    const response = await axios.post(
      API_URL,
      { inputs: inputText },
      {
        headers: {
          Authorization: `Bearer ${HUGGINGFACE_API_TOKEN}`,
        },
      }
    );
    console.log("Input text:", inputText); // debug
    console.log("Hugging Face response:", response.data); // debug
    return response.data[0]?.generated_text || "I'm here to listen whenever you're ready.";
  } catch (error) {
    console.error("Error fetching Hugging Face response:", error);
    return "Sorry, I couldn't process your request. Please try again later.";
  }
};
